# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: harbor-build

on:
  workflow_dispatch:
    inputs:
      build_version:
        description: "build_version"
        required: true
        default: "2.9.0"
env:
  version: ${{ github.event.inputs.build_version }}

jobs:

  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to Docker tencentyun Hub
      uses: docker/login-action@v2
      with:
        registry: hkccr.ccs.tencentyun.com
        username: ${{ secrets.TENCENT_DOCKER_USERNAME }}
        password: ${{ secrets.TENCENT_DOCKER_PASSWORD }}

    - name: Log in to Docker aliyun Hub
      uses: docker/login-action@v2
      with:
        registry: crpi-p2k20xc75i1dtww9.cn-guangzhou.personal.cr.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: package_offline
      id: image_tag
      run: |
        echo arch: $(arch)
        echo version: ${{ env.version }}
        id
        bash build.sh

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        build-args: version=${{ env.version }}
        tags: hank997/harbor-arm:${{ env.version }}
        platforms: linux/arm64
        file: Dockerfile
    - name: Build and push tencentyun Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        build-args: version=${{ env.version }}
        tags: hkccr.ccs.tencentyun.com/hank997/harbor-arm:${{ env.version }}
        platforms: linux/arm64
        file: Dockerfile

    - name: Build and push aliyun Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        build-args: version=${{ env.version }}
        tags: crpi-p2k20xc75i1dtww9.cn-guangzhou.personal.cr.aliyuncs.com/hank997/harbor:${{ env.version }}
        platforms: linux/arm64
        file: Dockerfile